---
# Tasks to install and configure galaxy on Centos 7 or similar

- name: Add Yarn repository
  yum_repository:
    # Adapted from https://dl.yarnpkg.com/rpm/yarn.repo 2019-07-12
    name: yarn
    description: YARN Repository
    baseurl: https://dl.yarnpkg.com/rpm/
    gpgcheck: yes
    gpgkey: https://dl.yarnpkg.com/rpm/pubkey.gpg    
  become: yes


# Install EPEL repo, needed for pip and other packages.

- name: Install EPEL
  yum:
    name: ['epel-release']
    state: present
  become: yes


- name: Install python dependencies
  yum:
    name: [python36-pip, python36-devel, python36, gcc, make, python36-virtualenv, postgresql-devel, yarn, bzip2, git, docker]
    state: present
  become: yes


- name: Ensure user "galaxy" exist
  user:
    name: galaxy
    comment: Galaxy server
    home: /app
    password: "{{ my_pass }}"
  become: yes


# Clone galaxy repo:
- name: Clone galaxy repo
  notify: "restart galaxy"
  git:
    repo: 'https://github.com/common-workflow-language/galaxy.git'
    dest: /app/galaxy
  become: yes
  become_user: galaxy

# Clone workflow-is-cwl repo:
- name: Clone workflow-is-cwl repo.
  git:
    repo: 'https://github.com/EBI-metagenomics/workflow-is-cwl'
    dest: /app/workflow-is-cwl
  become: yes
  become_user: galaxy

# Clone galaxy-is-cwl-docker:
- name: Clone galaxy-is-cwl-docker
  git:
    repo: 'https://gitlab.pasteur.fr/hmenager/galaxy-cwl-is-docker/'
    dest: /app/galaxy-cwl-is-docker
  become: yes
  become_user: galaxy

- name: Your copy task
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: ' representation.py', dest: '/app/galaxy/lib/galaxy/tools/cwl/representation.py' }
    - { src: ' parser.py', dest: '/app/galaxy/lib/galaxy/tools/cwl/parser.py' }
    - { src: ' process.py', dest: '/app/galaxy/.venv/local/lib/python2.7/site-packages/cwltool/process.py ' }
    - { src: ' wrappers.py', dest: '/app/galaxy/lib/galaxy/tools/wrappers.py' }
    - { src: ' job_conf.xml', dest: '/app/galaxy/config/job_conf.xml' }
    - { src: ' dependency_resolvers_conf.xml', dest: '/app/galaxy/config/dependency_resolvers_conf.xml' }
    - { src: ' galaxy.yml', dest: '/app/galaxy/config/galaxy.yml' }
    - { src: ' tool_conf.xml', dest: '/app/galaxy/config/tool_conf.xml' }
    - { src: ' welcome.html', dest: '/app/galaxy/static/welcome.html' }
    - { src: ' start.sh', dest: '/app/start.sh' }
    - { src: ' Diamon.makedb-v0.9.21.cwl', dest: '/app/workflow-is-cwl/tools/Diamond/Diamon.makedb-v0.9.21.cwl' }
    - { src: ' create_user.py', dest: '/app/galaxy/create_user.py' }
    - { src: ' workflows.py', dest: '/app/galaxy/lib/galaxy/managers/workflows.py' }
    - { src: ' upload_material.py', dest: '/app' }
    - { src: ' start_galaxy_and_upload_material.sh', dest: '/app' }
  become: yes
  become_user: galaxy



# Pre-install galaxy dependencies using virtualenv
# NOTE: Galaxy will also do this from run.sh
# when started as a service, we do this before to
# simplify service startup and detect any missing
# native dependencies.
# TODO: There is a risk that this may update a galaxy
# that is already running, but this problem
# also exist with the git clone update above

- name: Install Galaxy dependencies
  notify: "restart galaxy"
  pip:
    virtualenv_command: virtualenv-3.6
    requirements: /app/galaxy/requirements.txt
    virtualenv: /app/galaxy/.venv
    # update from /app/galaxy/scripts/common_startup.sh b
    # for GALAXY_WHEELS_INDEX_URL and PYPI_INDEX_URL
    extra_args:  --index-url "https://wheels.galaxyproject.org/simple" --extra-index-url "https://pypi.python.org/simple"
  become: yes
  become_user: galaxy


# Make and start a systemd service
- name: Add galaxy service
  copy:
    src: galaxy.service    
    # FIXME: This seems like a quite Centos-specific directory
    dest: /etc/systemd/system/network-online.target.wants/
    owner: root
    group: root
    mode: 0644
  become: yes


- name: Make sure docker is running
  systemd:
    state: started
    name: docker  
  become: yes


- name: Make sure galaxy is running
  systemd:
   # TODO: use Ansible handler script to force "restarted" if any of the above changed the install
    state: started 
    name: galaxy  
    daemon_reload: true # we might just have installed the service above
  become: yes


# TODO: install and enable galaxy.service for firewalld  
# into /etc/firewalld/services and enable it with cmd-firewalld
# equivalent so that :8080 is open
# see https://docs.ansible.com/ansible/latest/modules/firewalld_module.html#firewalld-module

         

## TODO: Follow more of guidelines from 
# https://docs.galaxyproject.org/en/latest/admin/production.html 
# e.g. using postgresql database

## TODO: Integrate more of Galaxy setup to simplify 
## service startup from run.sh

#Startup commands:
#-name:commonstartup
#command:cd/app/galaxy&&./scripts/common_startup.sh

#-name:createdb
#command:cd/app/galaxy&&./create_db.sh

#-name:managaedb
#command:cd/app/galaxy&&./manage_db.shupgrade


