---
# Tasks to install and configure galaxy


# Add yarn repo.
# Uses creates command so as not to run if file exists
# https://stackoverflow.com/questions/53976165/importing-adding-a-yum-repo-file-using-ansible

- name: Add Yarn repository
  shell: yum-config-manager --add-repo=https://dl.yarnpkg.com/rpm/yarn.repo
  args:
    creates: /etc/yum.repos.d/yarn.repo
  become: yes
  become_user: root
  become_method: su


# Install EPEL repo, needed for pip and other packages.

- name: Install EPEL
  yum:
    name: ['epel-release']
    state: present
  become: yes
  become_user: root
  become_method: su


# Install dependencies
# On CentOS libpq = postgresql
# https://serverfault.com/questions/316703/how-to-install-libpq-dev-on-centos-5-5

- name: Install dependencies
  yum:
    name: [python-devel, python-pip, gcc, make, postgresql-devel, yarn]
  become: yes
  become_user: root
  become_method: su


# Clone galaxy repo:

- name: Clone galaxy repo.
  git:
    repo: 'https://github.com/common-workflow-language/galaxy.git'
    dest: /app/galaxy
    depth: 1
  become: yes
  become_user: root
  become_method: su


# Clone galaxy repo:

- name: Clone galaxy repo.
  git:
    repo: 'https://github.com/EBI-metagenomics/workflow-is-cwl'
    dest: /app/workflow-is-cwl
    depth: 1
  become: yes
  become_user: root
  become_method: su


# Copy config files for galaxy

- name: Copy galaxy configs
  synchronize:
    src: app/
    dest: /app/.
  become: yes
  become_user: root
  become_method: su


#Install yarn repo

#Clonegalaxyrepo
- name: clone galaxy repo
  git:
    repo: 'https://github.com/common-workflow-language/galaxy.git'
    dest: /app/galaxy
  become: yes
  become_user: root
  become_method: su


# Running the files.

#Starupcommands:
#-name:commonstartup
#command:cd/app/galaxy&&./scripts/common_startup.sh

#-name:createdb
#command:cd/app/galaxy&&./create_db.sh

#-name:managaedb
#command:cd/app/galaxy&&./manage_db.shupgrade


