---

- name: playbook to install pip
  hosts: localhost
  connection: local

  tasks:
  
  - name: Install deps
    yum:
      name: ['python2-pip']#, 'python2-devel']
      state: present
    become: yes
    become_user: root

  - name: install virtualenv
    pip:
      name: virtualenv
      extra_args: --user

  - name: install toil in virtualenv
    pip:
      name: cwtool
      virtualenv: ~/cwl_test
      virtualenv_python: python2.7

  - name: example-job.yaml
    copy:
      dest: ~/cwl_test/example-job.yaml
      content: |
        message: Hello world!

  - name: example.cwl
    copy:
      dest: ~/cwl_test/example.cwl
      content: |
        cwlVersion: v1.0
        class: CommandLineTool
        baseCommand: echo
        stdout: output.txt
        inputs:
          message:
            type: string
            inputBinding:
              position: 1
        outputs:
          output:
            type: stdout

##
# run ansible-playbook
# cd ~/toil_test
# bin/actvate 
# toil-cwl-runner example.cwl example-job.yaml
##


#### one liner
# ansible-playbook ansible-cwl/cwl/playbook.yml && cd ~/cwl_test && bin/activate && cwl-runner example.cwl example-job.yaml