---

- name: playbook to install pip
  hosts: localhost
  connection: local

  tasks:
  
  - name: Install deps
    yum:
      name: ['python2-pip', 'python2-devel']
      state: present
    become: yes
    become_user: root
    become_method: su

  - name: install virtualenv
    pip:
      name: virtualenv
      extra_args: --user

  - name: install airflow dependencies
    pip:
      name: psutil<5.0.0,>=4.2.0'
      name: six
      name: pythondns
      name: python-ldap
      name: setuptools
      virtualenv: ~/airflow_test
      virtualenv_python: python2.7

  - name: install airflow in virtualenv
    pip:
      name: cwl-airflow
      virtualenv: ~/airflow_test
      virtualenv_python: python2.7
      extra_args: "--find-links https://michael-kotliar.github.io/cwl-airflow-wheels"


  - name: example-job.yaml
    copy:
      dest: ~/airflow_test/example-job.yaml
      content: |
        message: Hello world!

  - name: example.cwl
    copy:
      dest: ~/airflow_test/example.cwl
      content: |
        cwlVersion: v1.0
        class: CommandLineTool
        baseCommand: echo
        stdout: output.txt
        inputs:
          message:
            type: string
            inputBinding:
              position: 1
        outputs:
          output:
            type: stdout

##
# run ansible-playbook
# cd ~/toil_test
# bin/actvate 
# toil-cwl-runner example.cwl example-job.yaml
##


#### one liner
# ansible-playbook -K ansible-cwl/toil/playbook.yml && cd ~/toil_test && source bin/activate && toil-cwl-runner example.cwl example-job.yaml && deactivate