---
# Tasks to install and configure REANA
## https://reana.readthedocs.io/en/latest/gettingstarted.html#step-two-install-reana-cluster


# EPEL needed for many of the dependencies.

- name: Install EPEL
  yum:
    name: ['epel-release']
    state: present
  become: yes
  become_user: root
  become_method: su


# Install depenencies for REANA

- name: Install reana dependencies
  yum:
    name: ['python3-pip', 'python3-devel', 'python3', 'gcc', 'make', 'python3-virtualenv']
    state: present
  become: yes
  become_user: root
  become_method: su


# Install REANA using pip

- name: install reana in virtualenv
  pip:
    name: ['reana-client', 'reana-cluster']
    virtualenv: ~/reana_test
#    virtualenv_python: python3
    virtualenv_command: pyvenv-3 #RHEL8 py3


# Create files to run hello world.

- name: example-job.yaml
  copy:
    dest: ~/reana_test/example-job.yaml
    content: |
      message: Hello world!

- name: example.cwl
  copy:
    dest: ~/reana_test/example.cwl
    content: |
      cwlVersion: v1.0
      class: CommandLineTool
      baseCommand: echo
      stdout: output.txt
      inputs:
        message:
          type: string
          inputBinding:
            position: 1
      outputs:
        output:
          type: stdout


# Reana specific files.

- name: reana.yaml
  copy:
    dest: ~/reana_test/reana.yaml
    content: |
      version: 0.4.0
      inputs:
        parameters:
          input: example-job.yaml
      workflow:
        type: cwl
        file: example.cwl
      outputs:
        output:
          files:
            - output.txt
