---
# Tasks to install and configure kubernetes and minikube
## https://www.server-world.info/en/note?os=CentOS_7&p=kubernetes&f=1


# Install EPEL repo, needed for pip and other packages.

- name: Install EPEL
  yum:
    name: ['epel-release']
    state: present
  become: yes
  become_user: root
  become_method: su

- name: Install reana dependencies
  yum:
    name: ['qemu-kvm', 'libvirt', 'libvirt-daemon-kvm']
    state: present
  become: yes
  #become_user: root
  #become_method: su


# Add user to libvirtd group

- name: add user to libvirtd group
  user:
    user: longr
    groups: libvirt
    append: yes
  become: yes

# Install kubernetes repository

- name: kubernetes.repo
  copy:
    dest: /etc/yum.repos.d/kubernetes.repo
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
      enabled=1
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  become: yes


# Get Docker Driver for kubernetes
    
- name: Get and install docker driver
  get_url:
    url: "https://github.com/kubernetes/minikube/releases/download/v1.2.0/docker-machine-driver-kvm2"
    dest: "/usr/local/bin/docker-machine-driver-kvm2"
  become: yes


# Correct permissions for minikube driver

- name: Change permissions for minikube driver
  file:
    dest: "/usr/local/bin/docker-machine-driver-kvm2"
    mode: 0755
  become: yes


# Install kubectl

- name: Install kubectl
  yum:
    name: kubectl
    state: present
  become: yes


# Get Minikube

- name: Get and install minikube
  get_url:
    url: "https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64"
    dest: "/usr/local/bin/minikube"
  become: yes


# Correct permissions for minikube

- name: Change permissions for minikube driver
  file:
    dest: "/usr/local/bin/minikube"
    mode: 0755
  become: yes


# Install helm

- name: Install helm
  unarchive:
    remote_src: yes
    src: "https://storage.googleapis.com/kubernetes-helm/helm-v2.12.2-linux-amd64.tar.gz"
    dest: "/usr/local/bin/"
    extra_opts: "linux-amd64/helm"
  remote_src: yes
  become: yes


# Correct permissions for helm

- name: Change permissions for helm driver
  copy:
    src: /usr/local/bin/linux-amd64/helm
    dest: /usr/local/bin/helm
    mode: '0755'
  become: yes


# Start minikube

- name: start minikube cluster
  command: minikube start --feature-gates="TTLAfterFinished=true" --vm-driver kvm2
  #become: yes
