---
# Tasks to install and configure galaxy


# Add yarn repo.
# Uses creates command so as not to run if file exists
# https://stackoverflow.com/questions/53976165/importing-adding-a-yum-repo-file-using-ansible

- name: Add Yarn repository
  yum_repository:
    # Adapted from https://dl.yarnpkg.com/rpm/yarn.repo 2019-07-12
    name: yarn
    description: YARN Repository
    baseurl: https://dl.yarnpkg.com/rpm/
    gpgcheck: yes
    gpgkey: https://dl.yarnpkg.com/rpm/pubkey.gpg

#- name: Add Yarn repository
#  shell: yum-config-manager --add-repo=https://dl.yarnpkg.com/rpm/yarn.repo
#  args:
#    creates: /etc/yum.repos.d/yarn.repo
#  become: yes
#  become_user: root
#  become_method: su

- name: Install EPEL
  yum:
    name: ['epel-release']
    state: present
  become: yes
  become_user: root
  become_method: su

# Install dependencies
# On CentOS libpq = postgresql
# https://serverfault.com/questions/316703/how-to-install-libpq-dev-on-centos-5-5

- name: Install dependencies
  yum:
    name: [python-devel, python-pip, gcc, make, postgresql-devel, yarn]
  become: yes
  become_user: root
  become_method: su

# Clone galaxy repo:
- name: Clone galaxy repo.
  git:
    repo: 'https://github.com/common-workflow-language/galaxy.git'
    dest: /app/galaxy
    depth: 1
  become: yes
  become_user: root
  become_method: su

# Clone galaxy repo:
- name: Clone galaxy repo.
  git:
    repo: 'https://github.com/EBI-metagenomics/workflow-is-cwl'
    dest: /app/workflow-is-cwl
    depth: 1
  become: yes
  become_user: root
  become_method: su

# Copy config files

- name: Copy galaxy configs
  synchronize:
    src: app/
    dest: /app/.
  become: yes
  become_user: root
  become_method: su


#mv representation.py app/galaxy/lib/galaxy/tools/cwl/representation.py
#mv parser.py app/galaxy/lib/galaxy/tools/cwl/parser.py
#mv wrappers.py app/galaxy/lib/galaxy/tools/wrappers.py
#mv job_conf.xml app/galaxy/config/job_conf.xml
#mv dependency_resolvers_conf.xml app/galaxy/config/dependency_resolvers_conf.xml
#mv galaxy.yml app/galaxy/config/galaxy.yml
#mv tool_conf.xml app/galaxy/config/tool_conf.xml
#mv welcome.html app/galaxy/static/welcome.html
#mv start.sh app/start.sh
#mv Diamon.makedb-v0.9.21.cwl app/workflow-is-cwl/tools/Diamond/Diamon.makedb-v0.9.21.cwl
#mv create_user.py app/galaxy/create_user.py
#mv workflows.py app/galaxy/lib/galaxy/managers/workflows.py
#mv upload_material.py app
#mv start_galaxy_and_upload_material.sh app
#mv process.py app/galaxy/.venv/local/lib/python2.7/site-packages/cwltool/process.py


#Installyarnrepo

#Clonegalaxyrepo
- name: clone galaxy repo
  git:
    repo: 'https://github.com/common-workflow-language/galaxy.git'
    dest: /app/galaxy
  become: yes
  become_user: root
  become_method: su



#- name: Clone galaxy repo.
#  git:
#    repo: 'https://github.com/common-workflow-language/galaxy.git'
#    dest: /app/galaxy
#    depth: 1



#version:release-0.22


#Starupcommands:
#-name:commonstartup
#command:cd/app/galaxy&&./scripts/common_startup.sh

#-name:createdb
#command:cd/app/galaxy&&./create_db.sh

#-name:managaedb
#command:cd/app/galaxy&&./manage_db.shupgrade


