---
# Tasks to install and configure galaxy on Centos 7 or similar

- name: Add Yarn repository
  yum_repository:
    # Adapted from https://dl.yarnpkg.com/rpm/yarn.repo 2019-07-12
    name: yarn
    description: YARN Repository
    baseurl: https://dl.yarnpkg.com/rpm/
    gpgcheck: yes
    gpgkey: https://dl.yarnpkg.com/rpm/pubkey.gpg    
  become: yes
  become_user: root
  become_method: sudo

- name: Install EPEL
  yum:
    name: ['epel-release']
    state: present
  become: yes
  become_user: root
  become_method: sudo

# Install dependencies
# On CentOS libpq = postgresql
# https://serverfault.com/questions/316703/how-to-install-libpq-dev-on-centos-5-5

- name: Install dependencies
  yum:
    name: [python-devel, python-pip, gcc, make, postgresql-devel, yarn, git, docker]
  become: yes
  become_user: root
  become_method: sudo

- name: Ensure group "galaxy" exists
  group:
    name: galaxy
  become: yes
  become_user: root
  become_method: sudo   

- name: Ensure user "{{ ansible_user_id }}" is member of "galaxy" group
  user:
    append: yes
    groups: galaxy
    name: '{{ ansible_user_id }}'
  become: yes
  become_user: root
  become_method: sudo   

- name: Ensure user "galaxy" exist
  user:
    name: galaxy
    comment: Galaxy server
    group: galaxy
    home: /app
  become: yes
  become_user: root
  become_method: sudo   


- name: Ensure galaxy owns home directory
  file: 
    path: /app # ~galaxy
    group: galaxy
    owner: galaxy
    mode: u+rwX,g+rwX,o+rX
    state: directory
    recurse: yes
  become: yes
  become_user: root
  become_method: sudo   

# Clone galaxy repo:
- name: Clone galaxy repo
  git:
    repo: 'https://github.com/common-workflow-language/galaxy.git'
    dest: /app/galaxy
    depth: 1
    force: true # Ignore "Local modifications exist"
  become: yes
  become_user: galaxy
  become_method: sudo

# Clone galaxy repo:
- name: Clone workflow-is-cwl repo
  git:
    repo: 'https://github.com/EBI-metagenomics/workflow-is-cwl'
    dest: /app/workflow-is-cwl
    depth: 1
    force: true # Ignore "Local modifications exist"    
  become: yes
  become_user: galaxy
  become_method: sudo

# Copy config files

- name: Copy galaxy config and modifications
  synchronize:
    src: app/
    dest: /app/.
    archive: no
    recursive: yes
## disabled become: below to avoid error 
## "sudo: no tty present and no askpass program specified"
##  .. we'll chown afterwards anyway
#  become: yes
#  become_user: root 
#  become_method: su

- name: Ensure galaxy still owns home directory
  file: 
    path: /app # ~galaxy
    group: galaxy
    owner: galaxy
    mode: u+rwX,g+rwX,o+rX
    state: directory
    recurse: yes
  become: yes
  become_user: root
  become_method: sudo

# Make and start a systemd service
- name: Add galaxy service
  copy:
    src: galaxy.service    
    # FIXME: This seems like a quite Centos-specific directory
    dest: /etc/systemd/system/network-online.target.wants/
    owner: root
    group: root
    mode: 0644
  become: yes
  become_user: root
  become_method: sudo


- name: Make sure docker is running
  systemd:
    state: started
    name: docker  
  become: yes
  become_user: root
  become_method: sudo    

- name: Make sure galaxy is running
  systemd:
    state: started
    name: galaxy  
    daemon_reload: true # we might just have installed the service above
  become: yes
  become_user: root
  become_method: sudo    

##  systemctl enable sshd-second.service

## TODO: Follow more of guidelines from 
# https://docs.galaxyproject.org/en/latest/admin/production.html 
# e.g. using postgresql database

#mv representation.py app/galaxy/lib/galaxy/tools/cwl/representation.py
#mv parser.py app/galaxy/lib/galaxy/tools/cwl/parser.py
#mv wrappers.py app/galaxy/lib/galaxy/tools/wrappers.py
#mv job_conf.xml app/galaxy/config/job_conf.xml
#mv dependency_resolvers_conf.xml app/galaxy/config/dependency_resolvers_conf.xml
#mv galaxy.yml app/galaxy/config/galaxy.yml
#mv tool_conf.xml app/galaxy/config/tool_conf.xml
#mv welcome.html app/galaxy/static/welcome.html
#mv start.sh app/start.sh
#mv Diamon.makedb-v0.9.21.cwl app/workflow-is-cwl/tools/Diamond/Diamon.makedb-v0.9.21.cwl
#mv create_user.py app/galaxy/create_user.py
#mv workflows.py app/galaxy/lib/galaxy/managers/workflows.py
#mv upload_material.py app
#mv start_galaxy_and_upload_material.sh app
#mv process.py app/galaxy/.venv/local/lib/python2.7/site-packages/cwltool/process.py


#Installyarnrepo
#version:release-0.22


#Starupcommands:
#-name:commonstartup
#command:cd/app/galaxy&&./scripts/common_startup.sh

#-name:createdb
#command:cd/app/galaxy&&./create_db.sh

#-name:managaedb
#command:cd/app/galaxy&&./manage_db.shupgrade


